print("Please input your name")
name = input()
print("Nice to meet you " + name)
print("\n")
print("How old are you, " + name)
age = input()
x = int(age)
if (x <= 20) : print("you are young "+ name )
else : print("you are old " + name)